import asyncio
import uuid
import random
from app.core.database import async_session_factory
from app.models.social import Post
from app.models.user import User
from app.models.community import Community

# 🛠️ CONFIG: Set these to IDs that exist in your DB!
COMMUNITY_ID = uuid.UUID("YOUR_COMMUNITY_ID_HERE") 
USER_ID = uuid.UUID("YOUR_USER_ID_HERE") 

async def seed_posts():
    async with async_session_factory() as session:
        print(f"🌱 Seeding 50 posts for Community {COMMUNITY_ID}...")
        
        for i in range(50):
            # Simulate different layouts
            media = []
            roll = random.random()
            if roll > 0.8: media = ["https://picsum.photos/400/300"] # 1 Image
            elif roll > 0.6: media = ["https://picsum.photos/400/600", "https://picsum.photos/400/400"] # 2 Images
            elif roll > 0.5: media = ["https://picsum.photos/400/300", "https://picsum.photos/400/400", "https://picsum.photos/400/500"] # 3 Images
            
            post = Post(
                community_id=COMMUNITY_ID,
                author_id=USER_ID,
                content=f"Post #{50 - i}: This is a test message generated by the seeder. #Resinen",
                media_urls=media,
                like_count=random.randint(0, 100),
                comment_count=random.randint(0, 20)
            )
            session.add(post)
        
        await session.commit()
        print("✅ Done! Feed is populated.")

if __name__ == "__main__":
    asyncio.run(seed_posts())