import asyncio
import httpx
import random
from datetime import datetime, timedelta, timezone
from sqlalchemy import text
from sqlmodel import SQLModel
from app.core.database import async_session_factory, engine 
from app.core.security import get_password_hash
from app.models.user import User

# --- CONFIGURATION ---
BASE_URL = "http://localhost:8000/api/v1"

# --- PERSONAS ---
PERSONAS = [
    {"email": "admin@resinen.com", "pass": "admin123", "name": "Resinen Architect", "role": "superuser"},
    {"email": "alice@resinen.com", "pass": "password123", "name": "Alice Builder", "role": "user"},
    {"email": "bob@resinen.com", "pass": "password123", "name": "Bob The Critic", "role": "user"},
    {"email": "charlie@resinen.com", "pass": "password123", "name": "Charlie Newbie", "role": "user"},
    {"email": "diana@resinen.com", "pass": "password123", "name": "Diana Pro", "role": "user"},
]

async def wipe_and_bootstrap_db():
    """Wipes the DB iteratively to avoid permission errors and seeds users."""
    print("\n🔥 [DB] WIPING DATABASE (Iterative Drop)...")
    async with engine.begin() as conn:
        # 1. DROP ALL TABLES SAFELY
        result = await conn.execute(text("SELECT tablename FROM pg_tables WHERE schemaname = 'public'"))
        tables = result.scalars().all()
        for table in tables:
            await conn.execute(text(f'DROP TABLE IF EXISTS "public"."{table}" CASCADE'))

        # 2. RE-CREATE SCHEMA
        print("   -> Re-creating tables from SQLModel metadata...")
        await conn.run_sync(SQLModel.metadata.create_all)
    
    print("👤 [DB] BOOTSTRAPPING USER PERSONAS...")
    async with async_session_factory() as session:
        for p in PERSONAS:
            user = User(
                email=p["email"],
                full_name=p["name"],
                hashed_password=get_password_hash(p["pass"]),
                is_superuser=(p["role"] == "superuser"),
                is_active=True,
                reputation_score=random.randint(50, 500) if p["role"] != "superuser" else 9999
            )
            session.add(user)
        await session.commit()
        print(f"✅ Created {len(PERSONAS)} users in the database.")

async def login_user(client, email, password):
    try:
        # NOTE: Matches api.py prefix="/auth" and auth.py endpoint="/login"
        res = await client.post("/auth/login", data={"username": email, "password": password})
        
        if res.status_code != 200:
            print(f"❌ Login failed for {email} (Status {res.status_code}): {res.text}")
            return None
            
        token = res.json()["access_token"]
        return {"Authorization": f"Bearer {token}"}
    except Exception as e:
        print(f"❌ Connection error logging in {email}: {str(e)}")
        return None

async def seed_via_api():
    # 1. Reset DB
    await wipe_and_bootstrap_db()
    
    print(f"\n🚀 [API] STARTING EVOLUTION VIA: {BASE_URL}")
    async with httpx.AsyncClient(base_url=BASE_URL, timeout=60.0) as client:
        
        # 2. AUTHENTICATION
        print("🔑 [AUTH] Logging in all personas...")
        tokens = {}
        for p in PERSONAS:
            auth_header = await login_user(client, p["email"], p["pass"])
            if auth_header:
                tokens[p["email"]] = auth_header
            else:
                print("⚠️ Critical: Could not login. Is the server running?")
                return

        # Shortcuts
        admin_h = tokens.get("admin@resinen.com")
        alice_h = tokens.get("alice@resinen.com")
        bob_h = tokens.get("bob@resinen.com")
        charlie_h = tokens.get("charlie@resinen.com")
        diana_h = tokens.get("diana@resinen.com")

        if not admin_h: return

        # =========================================================================
        # 🌍 WORLD 1: THE NEXUS (Social & Governance Focus)
        # =========================================================================
        print("\n🌍 [COMMUNITY] Creating 'The Nexus'...")
        nexus_res = await client.post("/communities/", headers=admin_h, json={
            "name": "The Nexus",
            "slug": "nexus",
            "description": "Total System Validation World.",
            "primary_color": "#000000",
            "icon_url": "globe"
        })
        
        if nexus_res.status_code != 200:
            print(f"❌ Failed to create community: {nexus_res.text}")
            return
            
        nexus_id = nexus_res.json()["id"]

        # --- SOCIAL ENGINE ---
        print("   💬 [Social] Creating threaded conversations...")
        p1 = await client.post("/social/posts", headers=admin_h, json={
            "community_id": nexus_id,
            "title": "Welcome to the Simulation",
            "content": "This world is being generated by code. Confirm existence.",
            "is_pinned": True
        })
        if p1.status_code == 200:
            p1_id = p1.json()["id"]
            await client.post(f"/social/posts/{p1_id}/comments", headers=alice_h, json={"content": "Alice reporting in! 🫡"})
            c_bob = await client.post(f"/social/posts/{p1_id}/comments", headers=bob_h, json={"content": "latency seems high..."})
            if c_bob.status_code == 200:
                c_bob_id = c_bob.json()["id"]
                await client.post(f"/social/comments/{c_bob_id}/like", headers=admin_h)

        # --- GOVERNANCE ENGINE ---
        print("   ⚖️ [Governance] Holding an election...")
        prop = await client.post(f"/governance/{nexus_id}/proposals", headers=alice_h, json={
            "title": "Adopt Dark Mode by Default?",
            "description": "Should we force dark mode on all new interfaces?",
            "ends_at": (datetime.now(timezone.utc) + timedelta(days=7)).isoformat()
        })
        if prop.status_code == 200:
            prop_id = prop.json()["id"]
            await client.post(f"/governance/proposals/{prop_id}/vote", headers=bob_h, json={"choice": "no"})
            await client.post(f"/governance/proposals/{prop_id}/vote", headers=charlie_h, json={"choice": "yes"})
        else:
            print(f"   ⚠️ Governance failed: {prop.status_code} (Check api.py!)")

        # =========================================================================
        # 🛡️ WORLD 2: CODE GUILD
        # =========================================================================
        print("\n🌍 [COMMUNITY] Creating 'Code Guild'...")
        # FIX: Switched from diana_h to admin_h because of "Resinen Federal Authority" lock
        guild_res = await client.post("/communities/", headers=admin_h, json={
            "name": "Code Guild",
            "slug": "codex",
            "description": "Where builders unite.",
            "primary_color": "#6366f1",
            "icon_url": "code"
        })
        
        if guild_res.status_code != 200:
            print(f"❌ Failed to create Code Guild: {guild_res.text}")
            return
            
        guild_id = guild_res.json()["id"]

        # --- GUILD ENGINE ---
        print("   💰 [Guild] Posting bounties & projects...")
        # Diana can POST content, she just couldn't create the community
        await client.post(f"/guild/{guild_id}/bounties", headers=diana_h, json={
            "title": "Fix the Memory Leak",
            "description": "There is a leak in the websocket service.",
            "reward_text": "$500 USD"
        })

        # --- REFERRAL/SERVICE ENGINE ---
        print("   🤝 [Referral] Setting up member services...")
        svc = await client.post(f"/referral/{guild_id}/services", headers=bob_h, json={
            "title": "Senior Code Auditor",
            "description": "I will ruthlessly judge your codebase.",
            "contact_info": "bob@audit.com"
        })
        if svc.status_code == 200:
            svc_id = svc.json()["id"]
            await client.post(f"/referral/services/{svc_id}/vouch", headers=admin_h, json={
                "comment": "Bob is mean but accurate."
            })

        # --- LISTINGS (BAZAAR) ENGINE ---
        print("   🏷️ [Listings] Posting items for sale...")
        await client.post(f"/listings/{guild_id}/items", headers=alice_h, json={
            "title": "Mechanical Keyboard",
            "description": "Cherry MX Blue switches.",
            "price_display": "$100",
            "link_url": "https://example.com"
        })

        # =========================================================================
        # ⚔️ WORLD 3: THUNDERDOME
        # =========================================================================
        print("\n🌍 [COMMUNITY] Creating 'Thunderdome'...")
        arena_res = await client.post("/communities/", headers=admin_h, json={
            "name": "Thunderdome",
            "slug": "thunder",
            "description": "Sports, Bets, and Secrets.",
            "primary_color": "#ef4444",
            "icon_url": "zap"
        })
        
        if arena_res.status_code != 200:
            print(f"❌ Failed to create Thunderdome: {arena_res.text}")
            return

        arena_id = arena_res.json()["id"]

        # --- ARENA ENGINE ---
        print("   🏆 [Arena] Configuring teams & matches...")
        t1 = (await client.post(f"/arena/{arena_id}/teams", headers=admin_h, json={"name": "Red Dragons", "short_code": "RED", "color": "#ff0000"})).json()
        t2 = (await client.post(f"/arena/{arena_id}/teams", headers=admin_h, json={"name": "Blue Knights", "short_code": "BLU", "color": "#0000ff"})).json()
        
        match = await client.post(f"/arena/{arena_id}/matches", headers=admin_h, json={
            "team_a_id": t1["id"],
            "team_b_id": t2["id"],
            "start_time": (datetime.now(timezone.utc) + timedelta(hours=1)).isoformat(),
            "status": "scheduled"
        })
        if match.status_code == 200:
            match_id = match.json()["id"]
            await client.post(f"/arena/matches/{match_id}/predict", headers=charlie_h, json={"picked_team_id": t1["id"]})

        # --- CLUB ENGINE ---
        print("   🎉 [Club] Organizing a watch party...")
        event = await client.post(f"/club/{arena_id}/events", headers=admin_h, json={
            "title": "Finals Watch Party",
            "description": "Free drinks for winners.",
            "location_name": "The Metaverse Bar",
            "start_time": (datetime.now(timezone.utc) + timedelta(days=2)).isoformat()
        })
        if event.status_code == 200:
            event_id = event.json()["id"]
            await client.post(f"/club/events/{event_id}/rsvp", headers=bob_h, json={"status": "going"})

    print("\n✅ SUPER SEED COMPLETE. THE SIMULATION IS RUNNING.")

if __name__ == "__main__":
    asyncio.run(seed_via_api())